--Câu 18
    select count(*)
    from dean
--Câu 19
    select * from DEAN,PHONGBAN where DEAN.PHONG = PHONGBAN.MAPHG
--Câu 20
    select count(*) as 'Số lượng các phòng ban tham gia chủ trì đề án' 
    from DEAN,PHONGBAN where DEAN.PHONG = PHONGBAN.MAPHG
--Câu 21
    select count(*) as 'Số lượng đề án do phòng Nghiên Cứu chủ trì' 
    from DEAN inner join PHONGBAN on DEAN.PHONG = PHONGBAN.MAPHG 
    where PHONGBAN.TENPHG = N'Nghiên cứu'
--Câu 22
    select avg(LUONG) as 'Lương Trung Bình của các NV nữ'
	from NHANVIEN
	where phai like N'Nữ'
--Câu 23
    select count(*) as 'Số thân nhân của tiến'
	from NHANVIEN,THANNHAN
	where MANV=MA_NVIEN and HONV = N'Đinh' and TENLOT=N'Bá' and TENNV=N'Tiến'
--Câu 24
    select TOP 3 HONV + ' ' + TENLOT + ' ' + TENNV + ' ' 
    as 'Họ và tên',year(NGSINH) 
    as 'Năm sinh' from NHANVIEN
    ORDER BY year(NGSINH)
--Câu 25
    SELECT DEAN.MADA, COUNT(DEAN.MADA) AS 'Số lượng công việc'
    FROM DEAN, CONGVIEC
    WHERE DEAN.MADA = CONGVIEC.MADA
    GROUP BY DEAN.MADA, DEAN.TENDEAN
--Câu 26
    SELECT DEAN.TENDEAN, COUNT(DEAN.MADA) AS 'Số lượng công việc'
    FROM DEAN, CONGVIEC
    WHERE DEAN.MADA = CONGVIEC.MADA
    GROUP BY DEAN.MADA, DEAN.TENDEAN
--Câu 27
    SELECT (NHANVIEN.HONV + ' ' + NHANVIEN.TENLOT + ' ' + NHANVIEN.TENNV) AS 'Họ tên nhân viên', COUNT(THANNHAN.MA_NVIEN) AS 'Số lượng thân nhân'
    FROM NHANVIEN, THANNHAN
    WHERE NHANVIEN.MANV = THANNHAN.MA_NVIEN
    GROUP BY (NHANVIEN.HONV + ' ' + NHANVIEN.TENLOT + ' ' + NHANVIEN.TENNV)
--Câu 28
    SELECT (NHANVIEN.HONV + ' ' + NHANVIEN.TENLOT + ' ' + NHANVIEN.TENNV) AS 'Họ tên nhân viên', COUNT(THANNHAN.MA_NVIEN) AS 'Số lượng thân nhân'
    FROM NHANVIEN, THANNHAN
    WHERE NHANVIEN.MANV = THANNHAN.MA_NVIEN
    GROUP BY (NHANVIEN.HONV + ' ' + NHANVIEN.TENLOT + ' ' + NHANVIEN.TENNV)
--Câu 29
    SELECT (NHANVIEN.HONV + ' ' + NHANVIEN.TENLOT + ' ' + NHANVIEN.TENNV) AS 'Họ tên nhân viên', COUNT(PHANCONG.MA_NVIEN) AS'Số lượng đề án tham gia'
    FROM NHANVIEN, DEAN, PHANCONG
    WHERE NHANVIEN.MANV = PHANCONG.MA_NVIEN AND DEAN.MADA = PHANCONG.MADA
    GROUP BY (NHANVIEN.HONV + ' ' + NHANVIEN.TENLOT + ' ' + NHANVIEN.TENNV)
--Câu 30
    SELECT PHONGBAN.MAPHG, PHONGBAN.TENPHG, AVG(NHANVIEN.LUONG) AS 'Lương trung bình'
    FROM NHANVIEN, PHONGBAN
    WHERE NHANVIEN.PHG = PHONGBAN.MAPHG
    GROUP BY PHONGBAN.MAPHG, PHONGBAN.TENPHG
--Câu 31
    SELECT PHONGBAN.TENPHG, COUNT(NHANVIEN.MANV) AS N'Số lượng nhân viên'
    FROM NHANVIEN, PHONGBAN
    WHERE NHANVIEN.PHG = PHONGBAN.MAPHG
    GROUP BY PHONGBAN.TENPHG
    HAVING AVG(NHANVIEN.LUONG)>5200000
--Câu 32
    SELECT PHONGBAN.TENPHG, COUNT(DEAN.PHONG) AS 'Số lượng đề án'
    FROM PHONGBAN, DEAN
    WHERE PHONGBAN.MAPHG = DEAN.PHONG
    GROUP BY PHONGBAN.TENPHG
--Câu 33
    SELECT PHONGBAN.TENPHG, (NHANVIEN.HONV + ' ' + NHANVIEN.TENLOT + ' ' + NHANVIEN.TENNV) 
    AS 'Họ tên trưởng phòng', COUNT(DEAN.PHONG) AS 'Số lượng đề án'
    FROM NHANVIEN, PHONGBAN, DEAN
    WHERE NHANVIEN.MANV = PHONGBAN.TRPHG AND PHONGBAN.MAPHG = DEAN.PHONG
    GROUP BY PHONGBAN.TENPHG, (NHANVIEN.HONV + ' ' + NHANVIEN.TENLOT + ' ' + NHANVIEN.TENNV)
--Câu 34
SELECT DEAN.MADA, DEAN.TENDEAN, COUNT(DEAN.MADA) AS 'Số lượng công việc'
FROM DEAN, CONGVIEC
WHERE DEAN.MADA = CONGVIEC.MADA
GROUP BY DEAN.MADA, DEAN.TENDEAN
